// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmrikdshgzndemrwrwsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtcmlrZHNoZ3puZGVtcndyd3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMjQ4NzksImV4cCI6MjA2NDcwMDg3OX0.kjOIV2VqEL8Kqzk4aTTX38i16ejRO9pCLtekqpi0JPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);